export const LOGIN_REQUESTS='LOGIN_REQUESTS'
export const LOGIN_FAIL='LOGIN_FAIL'
export const LOGIN_SUCCESS='LOGIN_SUCCESS'

export const REGISTER_REQUESTS='REGISTER_REQUESTS'
export const REGISTER_FAIL='REGISTER_FAIL'
export const REGISTER_SUCCESS='REGISTER_SUCCESS'

export const LOAD_USER_REQUESTS='LOAD_USER_REQUESTS'
export const LOAD_USER_FAIL='LOAD_USER_FAIL'
export const LOAD_USER_SUCCESS='LOAD_USER_SUCCESS'

export const LOGOUT_FAIL='LOGOUT_FAIL'
export const LOGOUT_SUCCESS='LOGOUT_SUCCESS'

export const CLEAR_ERRORS='CLEAR_ERRORS'